[build]
  command = "npm run build"
  publish = "dist"

# Headers pour PWA
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=0"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirections PWA - ORDRE CRITIQUE
[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = true

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/icons/*"
  to = "/icons/:splat"
  status = 200
  force = true

# SPA fallback (en dernier)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200